### ISSUE TITLE
Sidebar more beautiful

### ISSUE THREAD

**Issue by AlixFachin** [AlixFachin/kaji-buntan#2]
- Setting the `position` to `absolute` so that when the sidebar grows the main content doesn't shrink
- Setting the height to a fixed amount so that when the main content scrolls down the side bar is still displayed
- Enhancing the sidebar content with icons and other menus

**Comment by osoken** [comment]
MUI Drawer may help this issue.
https://mui.com/material-ui/react-drawer/

**Comment by hiro-ogawa** [comment]
https://github.com/AlixFachin/kaji-buntan/pull/19
最終的にサイドバーは不要になったかな
